name: CI for Microservices

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test-services:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        service: [user_service, notification_service]

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: 3.9

    - name: Install system dependencies
      run: sudo apt-get update && sudo apt-get install -y build-essential python3-dev

    - name: Install dependencies
      run: |
        cd ${{ matrix.service }}
        pip install -r requirements.txt

    - name: Run tests
      run: |
        cd ${{ matrix.service }}
        python test_app.py  # Or use pytest test_app.py if you're using Pytest
